Datacollection/app/hd/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextField, SubmitField
from wtforms.validators import DataRequired, Length


class CompanyInfoForm(FlaskForm):
    # Form to use a ticker or name ot ask for info
    name = StringField('Name', [DataRequired(), Length(min=2, message=('Input is to short'))])
    submit = SubmitField('Submit')

Datacollection/app/__init__.py
# app/__init__.py

from flask import Flask
import sqlalchemy

db = sqlalchemy()

# Initialize the app
app = Flask(__name__, instance_relative_config=True)
# app config
app.config.from_object(config.Config)

# Load the views
from app.main.routes import main
from app.hd.routes import hd

app.register_blueprint(main)
app.register_blueprint(hd)
# Load the config file
app.config.from_object('config')

Datacollection/app/hd/__init__.py
# only init file for python pachage.

Datacollection/app/hd/routes.py
from flask import render_template, request, Blueprint, redirect, url_for
from app.hd.forms import CompanyInfoForm

hd = Blueprint('hd', __name__)


@hd.route("/hisdata", methods=('GET', 'POST'))
def hisdata():
    form = CompanyInfoForm()
    if form.validate_on_submit():
        return redirect(url_for('succes'))
    return render_template('historicdata.html', title='Historic data', form=form)

Datacollection/app/main/__init__.py
# only init file for python pachage.

Datacollection/app/main/routes.py
from flask import render_template, request, Blueprint

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html', title='Main page')

Datacollection/app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
          integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <!-- CSS custom styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">


    <title>{{ title }}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.home') }}">Algorimic trading info</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Basics</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Stock board</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('hd.hisdata')}}">Historic infomation</a>
                </li>
            </ul>
        </div>
    </div>
</nav>



{% block contend %}


{% endblock contend %}

<!-- Optional JavaScript -->
<!-- Popper.js first, then Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"
        integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/"
        crossorigin="anonymous"></script>
</body>
</html>

Datacollection/app/templates/historicdata.html
{% extends 'base.html' %}

{% block contend %}

    <div class="container-md gy-5">

        <div class="row gy-5">
            <div class="col-sm">
                <div class="formwrapper">
                    <h2 class="title">Company Info</h2>
                    <form method="POST" action="/">
                        <div class="form-field">{{ form.name.label }} {{ form.name(size=20) }}</div>
                        {{ form.submit }}
                    </form>
                </div>
            </div>
            <div class="col-sm">
                <button type="button" class="btn btn-primary">2</button>
            </div>
            <div class="col-sm">
                <button type="button" class="btn btn-primary">3</button>
            </div>
        </div>

    </div>

{% endblock %}

Datacollection/app/templates/home.html
{% extends 'base.html' %}

{% block contend %}
<h1 class="alert">home</h1>
{% endblock %}